# Generated by Django 3.1.5 on 2021-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='covers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
